name: handson
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - pip:
    - folium==0.20.0
    - jupyterlab==4.4.9
    - loguru==0.7.3
    - matplotlib==3.10.0
    - missingno==0.5.2
    - numpy==2.1.0
    - pandas==2.3.2
    - plotly==6.3.0
    - seaborn==0.13.2
    - ydata-profiling==4.17.0