name: handson
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - pip:
    - branca==0.8.1
    - dill==0.4.0
    - folium==0.20.0
    - jupyterlab=4.4.9
    - loguru==0.7.3
    - matplotlib==3.10.0
    - missingno==0.5.2
    - numpy==2.1.0
    - pandas==2.3.2
    - pendulum==3.1.0
    - plotly==6.3.0
    - seaborn==0.13.2
    - session_info==v1.0.1
    - shap==0.48.0
    - sklearn==1.7.2
    - statsmodels==0.14.5
    - ydata_profiling==v4.17.0
    - yellowbrick==1.5